version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.parallel=false -Dorg.gradle.daemon=false'
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys: jars-{{ checksum "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Run plugin test
          command: |
            cd plugin
            ./../gradlew test
            cd ../

#      - run:
#          name: Run example build
#          command: |
#            cd example
#            ./../gradlew assemble
#            cd ../
